# Generated by Django 6.1.1 on 2026-09-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DojoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_fundacion', models.DateField()),
                ('distrito', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('jefe_instructor', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dojo',
                'db_table': 'dojo',
            },
        ),
        migrations.CreateModel(
            name='CompetidoresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('dni', models.CharField(max_length=8)),
                ('fecha_nacimiento', models.DateField()),
                ('grado', models.CharField(max_length=50)),
                ('fecha_grado', models.DateField()),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dojo_p', to='deportista.dojomodel')),
            ],
            options={
                'verbose_name': 'Competidores',
                'verbose_name_plural': 'Competidores',
                'db_table': 'competidores',
            },
        ),
    ]
