# Generated by Django 6.1.1 on 2026-09-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportista', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dojomodel',
            options={'verbose_name': 'Dojo', 'verbose_name_plural': 'Dojos'},
        ),
        migrations.AlterField(
            model_name='competidoresmodel',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='competidoresmodel',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
