# Generated by Django 6.1.1 on 2026-09-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deportista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampeonatoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_realizacion', models.DateField()),
                ('ranking', models.BooleanField(default=False)),
                ('departamento', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('distrito', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Campeonato',
                'db_table': 'campeonato',
            },
        ),
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('modalidad', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('nivel', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Categorias',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='ModalidadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campeonato_p', to='evento.campeonatomodel')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias_p', to='evento.categoriamodel')),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competidores_p', to='deportista.competidoresmodel')),
            ],
            options={
                'verbose_name': 'Modalidades',
                'db_table': 'modalidades',
            },
        ),
    ]
